spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:postgresql://localhost:5432/like"
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
jwt:
  secret: __L1k3
  expiration: 60000000